encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:name>", views.entry, name="entry"),
    path("search_results/<str:query>", views.search_results, name="search_results"),
    path("create", views.create, name="create"),
    path("edit/<str:name>", views.edit, name="edit"),
	path("random_entry", views.random_entry, name="random_entry"),
	path("error", views.error, name="error")
]

final/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include("shop.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mail/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    # API Routes
    path("emails", views.compose, name="compose"),
    path("emails/<int:email_id>", views.email, name="email"),
    path("emails/<str:mailbox>", views.mailbox, name="mailbox"),
]

project3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mail.urls'))
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
import markdown2
import random
import re

from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from random import randint

from . import util

from markdown2 import Markdown

class NewSearchForm(forms.Form):
	query = forms.CharField(label="Enter your query:")
class NewPageForm(forms.Form):
	entry_name = forms.CharField(label="Enter page name:") 
	entry_content = forms.CharField(widget=forms.Textarea(), label="Enter page content:") 
class EditPageForm(forms.Form):
	entry_content = forms.CharField(widget=forms.Textarea(), label="Edit page content:") 
	
	
def index(request):
	if request.method == "POST":
		page = "encyclopedia/index.html"
		url = search_form(request, page)
		return HttpResponseRedirect(url)
	else:
		return render(request, "encyclopedia/index.html", {
			"form": NewSearchForm(),
			"entries": util.list_entries()
		})

def entry(request, name):
	if request.method == "POST":
		page = "encyclopedia/entry.html"
		url = search_form(request, page)
		return HttpResponseRedirect(url)
	else:
		markdowner = Markdown()
		content_text = util.get_entry(name)
		if content_text:
			content = markdowner.convert(content_text)
			return render(request, "encyclopedia/entry.html", {
				"form": NewSearchForm(),
				"name": name,
				"content": content
			})
		else:
			return render(request, "encyclopedia/error.html", {
				"form": NewSearchForm(),
				"text": "Requested page is not found!"
			})
	
def search_results(request, query):
	if request.method == "POST":
		page = "encyclopedia/search_results.html"
		url = search_form(request, page)
		return HttpResponseRedirect(url)
	else:
		result_entries = []
		entries = util.list_entries()
		for i in range(0,len(entries)):
			entry = entries[i]
			entry_lower = entry.lower()
			if entry_lower.find(query.lower())>=0:
				result_entries.append(entry);
		return render(request, "encyclopedia/search_results.html", {
				"form": NewSearchForm(),
				"entries": result_entries
		})

def search_form(request, page):
	form = NewSearchForm(request.POST)
	if form.is_valid():
		query = form.cleaned_data["query"]
		entry_text = util.get_entry(query)
		if entry_text:
			url = reverse("encyclopedia:entry", kwargs={'name': query})
		else:
			url = reverse("encyclopedia:search_results", kwargs={'query': query})
		return url
	else:
		return render(request, page, {
			"form": form
        })	

def create(request):
	if request.method == "POST":
		form = NewPageForm(request.POST)
		if form.is_valid():
			entry_name = form.cleaned_data["entry_name"]
			entry_content = form.cleaned_data["entry_content"]
			existing_entry = util.get_entry(entry_name)
			if existing_entry:
				return render(request, "encyclopedia/error.html", {
					"form": NewSearchForm(),
					"text": "Such entry is already existing!"
				})
			else:
				util.save_entry(entry_name, entry_content)
				url = reverse("encyclopedia:entry", kwargs={'name': entry_name})
				return HttpResponseRedirect(url)	
		else:
			form = NewSearchForm(request.POST)
			page = "encyclopedia/create.html"
			url = search_form(request, page)
			return HttpResponseRedirect(url) 		
	else:
		return render(request, "encyclopedia/create.html", {
			"form": NewSearchForm(),
			"create_page_form": NewPageForm()
		})

def edit(request, name):
	if request.method == "POST":
		form = EditPageForm(request.POST)
		if form.is_valid():
			edited_entry_content = form.cleaned_data["entry_content"]
			util.save_entry(name, edited_entry_content)
			url = reverse("encyclopedia:entry", kwargs={'name': name})
			return HttpResponseRedirect(url)	
		else:
			form = NewSearchForm(request.POST)
			page = "encyclopedia/edit.html"
			url = search_form(request, page)
			return HttpResponseRedirect(url) 		
	else:		
		entry_content = '\r\n'.join(list(filter(None,util.get_entry(name).splitlines())))
		initial = {'entry_content': entry_content}
		return render(request, "encyclopedia/edit.html", {
			"form": NewSearchForm(),
			"entry_name": name,
			"edit_page_form": EditPageForm(initial=initial)
		})
	
		
def random_entry(request):
	all_entries = util.list_entries()
	len_entries = len(all_entries)-1
	random_number = randint(0, len_entries)
	random_entry = all_entries[random_number]
	entry_text = util.get_entry(random_entry)
	if entry_text:
		url = reverse("encyclopedia:entry", kwargs={'name': random_entry})
		return HttpResponseRedirect(url)	
	else:
		return render(request, "encyclopedia/error.html", {
			"form": NewSearchForm(),
			"text": "Something went wrong... Requested page is not found!"
		})

def error(request, text):		
	return render(request, "encyclopedia/error.html", {
		"form": NewSearchForm(),
		"text": text
	})

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Create new page</h1>

                <form method="post">
					{% csrf_token %}
					{{ create_page_form }}
					<button type="submit">Save</button>
                </form>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Edit "{{ entry_name }}" page</h1>

                <form method="post">
					{% csrf_token %}
					{{ edit_page_form }}
					<button type="submit">Save changes</button>
                </form>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

	{{ content|safe}}
	<a href="{% url 'encyclopedia:edit' name %}" class="a_button">Edit entry</a>

{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

	{{ text }}
	
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form method="post">
					{% csrf_token %}
					{{ form }}
					<button type="submit">Find it!</button>
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                   <a href="{% url 'encyclopedia:create' %}"> Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_entry' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search results</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
		{% empty %}
			<li>No matches</li>
        {% endfor %}
    </ul>

{% endblock %}